environments:
  build:
    pipelines:
      - app-build

pipelines:
  app-build:
    group: Poc-App
    label_template: "${COUNT}"
    locking: off
    materials:
      source:
        git: ssh://git@10.7.68.15:7999/pocgocd/poc.app.git
        branch: master
        auto_update: yes
        shallow_clone: yes
    stages:
      - build:
          fetch_materials: yes
          clean_workspace: yes
          jobs:
            docker_build:
              elastic_profile_id: "Docker"
              tasks:
                - exec:
                    command: make
                    arguments:
                      - "publish"